#!/bin/bash
# Pulls the latest daily report (generated by GitHub Actions) and fires a
# macOS notification with the headline. Run daily by a local LaunchAgent.
set -euo pipefail

REPO_DIR="/Users/nickgardone/Documents/Business/Career/ticket-price-tracker"
cd "$REPO_DIR"

git pull --quiet origin main

REPORT="$REPO_DIR/latest_report.txt"
if [ ! -f "$REPORT" ]; then
    osascript -e 'display notification "No report found yet" with title "Bills vs Dolphins Tickets"'
    exit 0
fi

RATING_LINE=$(grep -A1 "1) PRICE RATING" "$REPORT" | tail -1 | sed 's/^ *//' | sed 's/"/'"'"'/g')
PRICE_LINE=$(grep "SeatGeek:" "$REPORT" | head -1 | sed 's/^ *//' | sed 's/"/'"'"'/g')

osascript -e "display notification \"$PRICE_LINE\" with title \"Bills vs Dolphins Tickets\" subtitle \"$RATING_LINE\""
